const state={page:'dashboard', customers:[], leads:[], tasks:[], messages:[]};
const menu=[['dashboard','▦','Dashboard'],['customers','◎','Customers 360'],['leads','◈','Leads'],['pipeline','▤','Pipeline'],['inbox','✉','Unified Inbox'],['tasks','✓','Tasks'],['calls','☎','Calls'],['campaigns','⌁','Campaigns'],['reports','▥','Reports'],['integrations','⚙','Integrations']];
const $=s=>document.querySelector(s); const fmt=n=>'₹'+Number(n||0).toLocaleString('en-IN');
async function api(p,opt){const r=await fetch('/api/'+p,opt);return r.json()}
async function init(){
  $('#nav').innerHTML=menu.map(m=>`<button data-page="${m[0]}" onclick="go('${m[0]}')"><span>${m[1]}</span> &nbsp;${m[2]}</button>`).join('');
  $('#bottomNav').innerHTML=menu.slice(0,5).map(m=>`<button onclick="go('${m[0]}')"><span>${m[1]}</span>${m[2].replace('Customers 360','Customers')}</button>`).join('');
  [state.customers,state.leads,state.tasks,state.messages]=await Promise.all([api('customers'),api('leads'),api('tasks'),api('messages')]); go('dashboard');
}
function go(p){state.page=p; document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p)); render(); if(innerWidth<980) $('.sidebar').classList.remove('show')}
function title(h,s){return `<div class="pageTitle"><div><h1>${h}</h1><p>${s}</p></div></div>`}
async function render(){
  if(state.page==='dashboard') return dashboard(); if(state.page==='customers') return customers(); if(state.page==='leads') return leads(); if(state.page==='pipeline') return pipeline(); if(state.page==='inbox') return inbox(); if(state.page==='tasks') return tasks(); return placeholder(state.page);
}
async function dashboard(){ const d=await api('dashboard'); const hot=state.customers.filter(c=>c.status==='Hot'); $('#view').innerHTML=title('Command Center','One view of customers, leads, activity and sales.')+`
<div class="grid4"><div class="stat"><div class="label">CUSTOMERS</div><div class="num">${d.stats.customers}</div></div><div class="stat"><div class="label">ACTIVE LEADS</div><div class="num">${d.stats.leads}</div></div><div class="stat"><div class="label">OPEN TASKS</div><div class="num">${d.stats.openTasks}</div></div><div class="stat"><div class="label">PIPELINE VALUE</div><div class="num">${fmt(d.stats.pipelineValue)}</div></div></div>
<div class="two"><div class="card"><h3>Conversion Funnel</h3><div class="funnel">${['New','Qualified','Follow-up','Appointment','Won'].map(s=>`<div><b>${d.pipeline[s]||0}</b><span>${s}</span></div>`).join('')}</div></div><div class="card"><h3>Hot Customers</h3>${hot.map(c=>customerMini(c)).join('')||'<div class="empty">No hot customers</div>'}</div></div>
<div class="card" style="margin-top:14px"><h3>Recent Leads</h3>${leadTable(state.leads.slice(0,6))}</div>` }
function customers(){ $('#view').innerHTML=title('Customer 360','One customer, one identity, complete history across every channel.')+`<div class="card"><div class="tableWrap"><table class="table"><thead><tr><th>Customer</th><th>Mobile</th><th>Interest</th><th>Source</th><th>Score</th><th>Status</th><th>LTV</th></tr></thead><tbody>${state.customers.map(c=>`<tr onclick="openCustomer('${c.id}')" style="cursor:pointer"><td><b>${c.name}</b><div class="muted">${c.branch}</div></td><td>${c.mobile}</td><td>${c.interest}</td><td>${c.source}</td><td>${c.leadScore}</td><td><span class="chip ${c.status==='Hot'?'hot':c.status==='Warm'?'warm':''}">${c.status}</span></td><td>${fmt(c.ltv)}</td></tr>`).join('')}</tbody></table></div></div>`}
function leads(){ $('#view').innerHTML=title('Lead Management','Track every lead from first enquiry to conversion.')+`<div class="card">${leadTable(state.leads)}</div>`}
function leadTable(ls){return `<div class="tableWrap"><table class="table"><thead><tr><th>Customer</th><th>Source</th><th>Stage</th><th>Value</th><th>Next Follow-up</th></tr></thead><tbody>${ls.map(l=>{const c=state.customers.find(c=>c.id===l.customerId)||{};return `<tr><td><b>${c.name||l.customerId}</b><div class="muted">${c.mobile||''}</div></td><td>${l.source}</td><td><span class="chip">${l.stage}</span></td><td>${fmt(l.value)}</td><td>${new Date(l.nextFollowup).toLocaleString('en-IN')}</td></tr>`}).join('')}</tbody></table></div>`}
function pipeline(){const stages=['New','Qualified','Follow-up','Appointment','Won'];$('#view').innerHTML=title('Sales Pipeline','Visual lead journey and expected revenue.')+`<div class="kanban">${stages.map(s=>`<div class="column"><div class="columnTitle"><span>${s}</span><span>${state.leads.filter(l=>l.stage===s).length}</span></div>${state.leads.filter(l=>l.stage===s).map(l=>{let c=state.customers.find(c=>c.id===l.customerId)||{};return `<div class="deal"><b>${c.name||'Customer'}</b><div class="muted">${l.source}</div><div class="money">${fmt(l.value)}</div></div>`}).join('')}</div>`).join('')}</div>`}
function tasks(){ $('#view').innerHTML=title('Tasks & Follow-ups','Never miss the next customer action.')+`<div class="card"><div class="tableWrap"><table class="table"><thead><tr><th>Task</th><th>Customer</th><th>Type</th><th>Due</th><th>Status</th></tr></thead><tbody>${state.tasks.map(t=>{let c=state.customers.find(c=>c.id===t.customerId)||{};return `<tr><td><b>${t.title}</b></td><td>${c.name||''}</td><td>${t.type}</td><td>${new Date(t.due).toLocaleString('en-IN')}</td><td><span class="chip">${t.status}</span></td></tr>`}).join('')}</tbody></table></div></div>`}
function inbox(){let groups=[...new Set(state.messages.map(m=>m.customerId))];$('#view').innerHTML=title('Unified Inbox','WhatsApp, social, website and email conversations in one workspace.')+`<div class="card inbox"><div class="inboxList"><h3>Conversations</h3>${groups.map(id=>{let c=state.customers.find(c=>c.id===id)||{};let last=state.messages.filter(m=>m.customerId===id).slice(-1)[0];return `<div class="leadCard" onclick="showConversation('${id}')"><div class="person">${(c.name||'?')[0]}</div><div class="grow"><b>${c.name}</b><div class="muted">${last?.channel}: ${last?.text?.slice(0,30)||''}</div></div></div>`}).join('')}</div><div class="conversation" id="conversation"><div class="empty">Select a conversation</div></div><div class="inboxDetail"><h3>Customer</h3><div class="empty">Customer context will appear here.</div></div></div>`}
function showConversation(id){let c=state.customers.find(c=>c.id===id)||{};let msgs=state.messages.filter(m=>m.customerId===id);$('#conversation').innerHTML=`<h3>${c.name}</h3><div class="muted">${c.mobile} • ${c.interest}</div><div style="margin-top:18px">${msgs.map(m=>`<div class="bubble ${m.direction==='out'?'out':''}"><small>${m.channel}</small><br>${m.text}</div>`).join('')}</div>`}
function customerMini(c){return `<div class="leadCard" onclick="openCustomer('${c.id}')"><div class="person">${c.name[0]}</div><div class="grow"><b>${c.name}</b><div class="muted">${c.interest} • ${c.source}</div></div><b>${c.leadScore}</b></div>`}
async function openCustomer(id){let c=await api('customers/'+id); $('#view').innerHTML=`<div class="customerHero"><div><h2>${c.name} <span class="chip hot">${c.status}</span></h2><div class="muted">${c.mobile} • ${c.email} • ${c.branch}</div><div style="margin-top:8px"><b>${c.interest}</b> • ${c.budget} • Lead Score ${c.leadScore}/100</div></div><div class="actions"><button class="ghost">☎ Call</button><button class="ghost">💬 WhatsApp</button><button class="ghost">✓ Task</button><button class="primary">📅 Appointment</button></div></div><div class="tabs"><button class="active">Timeline</button><button>Conversations</button><button>Orders</button><button>Tasks</button></div><div class="two"><div class="card"><h3>Customer Timeline</h3><div class="timeline">${c.activities.map(a=>`<div class="event"><b>${a.text}</b><small>${a.type} • ${new Date(a.at).toLocaleString('en-IN')}</small></div>`).join('')}</div></div><div class="card"><h3>Customer Intelligence</h3><p><b>Source:</b> ${c.source}</p><p><b>Segment:</b> ${c.segment}</p><p><b>Interest:</b> ${c.interest}</p><p><b>Budget:</b> ${c.budget}</p><p><b>Lifetime Value:</b> ${fmt(c.ltv)}</p><p><b>Lead Score:</b> ${c.leadScore}/100</p></div></div>`}
function placeholder(p){$('#view').innerHTML=title(p[0].toUpperCase()+p.slice(1),'Module foundation ready for integration.')+`<div class="card empty"><h3>${p}</h3><p>This module is prepared in the navigation and can be connected next.</p></div>`}
function globalSearch(q){q=q.trim().toLowerCase(); if(!q) return; let c=state.customers.find(c=>[c.name,c.mobile,c.email,c.interest].some(v=>(v||'').toLowerCase().includes(q))); if(c) openCustomer(c.id)}
function toggleSidebar(){$('.sidebar').classList.toggle('show')}
function openAddLead(){ $('#modalWrap').classList.add('show'); $('#modal').innerHTML=`<h2>Create Lead</h2><div class="formGrid"><div class="field"><label>Customer Name</label><input id="n" placeholder="Name"></div><div class="field"><label>Mobile</label><input id="m" placeholder="Mobile"></div><div class="field"><label>Source</label><select id="s"><option>WhatsApp</option><option>Instagram</option><option>Website</option><option>Incoming Call</option><option>Abandoned Checkout</option></select></div><div class="field"><label>Interest</label><input id="i" placeholder="Antique Haram"></div><div class="field"><label>Budget</label><input id="b" placeholder="₹3L"></div><div class="field"><label>Lead Value</label><input id="v" type="number" placeholder="300000"></div></div><div class="modalActions"><button class="ghost" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveLead()">Create Lead</button></div>`}
function closeModal(){$('#modalWrap').classList.remove('show')}
async function saveLead(){let c=await api('customers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('#n').value,mobile:$('#m').value,email:'',branch:'',segment:'',source:$('#s').value,budget:$('#b').value,interest:$('#i').value,status:'New'})}); await api('leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customerId:c.id,source:$('#s').value,stage:'New',value:Number($('#v').value||0),assignedTo:'u2',nextFollowup:new Date(Date.now()+86400000).toISOString()})}); state.customers=await api('customers');state.leads=await api('leads');closeModal();go('leads')}
init();
