const http=require('http'),https=require('https'),fs=require('fs'),path=require('path'),url=require('url'),crypto=require('crypto');
const PORT=process.env.PORT||3000,ROOT=__dirname,DB_PATH=path.join(ROOT,'data','db.json'),PUBLIC=path.join(ROOT,'public');
const WEBHOOK_SECRET=process.env.CRM_WEBHOOK_SECRET||'';
const ADMIN_PASSWORD=process.env.CRM_PASSWORD||'';
const sessions=new Set();
function readDb(){return JSON.parse(fs.readFileSync(DB_PATH,'utf8'))}
function writeDb(db){fs.writeFileSync(DB_PATH,JSON.stringify(db,null,2))}
function send(res,status,data,type='application/json',headers={}){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store',...headers});res.end(type.includes('json')?JSON.stringify(data):data)}
function rawBody(req){return new Promise((resolve,reject)=>{let b='';req.on('data',d=>{b+=d;if(b.length>4e6)req.destroy()});req.on('end',()=>resolve(b));req.on('error',reject)})}
async function body(req){const b=await rawBody(req);if(!b)return{};const ct=req.headers['content-type']||'';if(ct.includes('application/x-www-form-urlencoded'))return Object.fromEntries(new URLSearchParams(b));try{return JSON.parse(b)}catch{return{raw:b}}}
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>{let [k,...v]=x.trim().split('=');return[k,v.join('=')]}))}
function authed(req){if(!ADMIN_PASSWORD)return true;return sessions.has(cookies(req).crm_session)}
function serveStatic(req,res){let p=url.parse(req.url).pathname;if(p==='/')p='/index.html';const file=path.resolve(PUBLIC,'.'+p);if(!file.startsWith(PUBLIC)||!fs.existsSync(file)||fs.statSync(file).isDirectory())return false;const ext=path.extname(file),types={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'application/javascript','.svg':'image/svg+xml'};send(res,200,fs.readFileSync(file),types[ext]||'application/octet-stream');return true}
function newId(prefix){return prefix+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function metricReport(db){const src={};for(const l of db.leads){const k=l.source||'Unknown';src[k]??={leads:0,value:0,won:0};src[k].leads++;src[k].value+=Number(l.value||0);if(l.stage==='Won')src[k].won++}return Object.entries(src).map(([source,v])=>({source,...v,conversion:v.leads?Math.round(v.won/v.leads*1000)/10:0})).sort((a,b)=>b.leads-a.leads)}
function normMobile(v){return String(v||'').replace(/\D/g,'').replace(/^91(?=\d{10}$)/,'').slice(-10)}
function sameMobile(a,b){a=normMobile(a);b=normMobile(b);return a&&b&&a===b}
function findCustomer(db,{mobile,email,externalId}={}){return db.customers.find(c=>(mobile&&sameMobile(c.mobile,mobile))||(email&&c.email&&c.email.toLowerCase()===String(email).toLowerCase())||(externalId&&c.externalIds&&Object.values(c.externalIds).includes(externalId)))}
function upsertCustomer(db,x={}){let c=findCustomer(db,x);if(!c){c={id:newId('c'),tenantId:'dar',name:x.name||'Unknown Customer',mobile:normMobile(x.mobile),email:x.email||'',branch:x.branch||'',segment:x.segment||'',ltv:0,leadScore:50,assignedTo:'u2',status:'New',source:x.source||'API',budget:x.budget||'',interest:x.interest||'',externalIds:{}};db.customers.push(c)}else{if(x.name&&(!c.name||c.name==='Unknown Customer'))c.name=x.name;if(x.email&&!c.email)c.email=x.email;if(x.source&&!c.source)c.source=x.source;if(x.interest)c.interest=x.interest;if(x.budget)c.budget=x.budget}if(x.externalId){c.externalIds??={};c.externalIds[x.provider||'external']=x.externalId}return c}
function addActivity(db,c,type,text,extra={}){db.activities??=[];db.activities.push({id:newId('a'),tenantId:'dar',customerId:c.id,type,text,at:extra.at||new Date().toISOString(),provider:extra.provider||'',externalId:extra.externalId||'',meta:extra.meta||{}})}
function addLead(db,c,x={}){db.leads??=[];const externalId=x.externalId||'';if(externalId&&db.leads.some(l=>l.externalId===externalId))return null;const recent=db.leads.find(l=>l.customerId===c.id&&l.source===(x.source||'API')&&l.stage!=='Won'&&Date.now()-new Date(l.createdAt||0).getTime()<86400000);if(recent&&!x.force)return recent;const l={id:newId('l'),tenantId:'dar',customerId:c.id,source:x.source||'API',stage:x.stage||'New',value:Number(x.value||0),assignedTo:x.assignedTo||'u2',nextFollowup:x.nextFollowup||new Date(Date.now()+86400000).toISOString(),createdAt:x.createdAt||new Date().toISOString(),externalId};db.leads.push(l);return l}
function addMessage(db,c,x={}){db.messages??=[];if(x.externalId&&db.messages.some(m=>m.externalId===x.externalId))return null;const m={id:newId('m'),tenantId:'dar',customerId:c.id,channel:x.channel||x.provider||'External',direction:x.direction||'in',text:x.text||'',at:x.at||new Date().toISOString(),externalId:x.externalId||'',provider:x.provider||''};db.messages.push(m);return m}
function addCall(db,c,x={}){db.calls??=[];if(x.externalId&&db.calls.some(a=>a.externalId===x.externalId))return null;const rec={id:newId('call'),customerId:c.id,direction:x.direction||'Incoming',provider:x.provider||'External',status:x.status||'Unknown',disposition:x.disposition||'',duration:Number(x.duration||0),owner:x.owner||'',recordingUrl:x.recordingUrl||'',externalId:x.externalId||'',at:x.at||new Date().toISOString(),from:x.from||'',to:x.to||'',rawStatus:x.rawStatus||''};db.calls.push(rec);addActivity(db,c,'Call',`${rec.direction} ${rec.provider} call – ${rec.status}${rec.duration?` (${rec.duration}s)`:''}`,{provider:rec.provider,externalId:rec.externalId,at:rec.at});if(['Missed','No Answer','Busy','Failed'].includes(rec.status)){addLead(db,c,{source:`${rec.provider} ${rec.status}`,externalId:rec.externalId?`lead-${rec.externalId}`:'',force:false});db.tasks??=[];if(!db.tasks.some(t=>t.customerId===c.id&&t.status==='Open'&&t.title.includes('missed call')))db.tasks.push({id:newId('t'),tenantId:'dar',customerId:c.id,title:`Follow up ${rec.provider} missed call`,type:'Call',due:new Date(Date.now()+3600000).toISOString(),status:'Open',owner:'u2'})}return rec}
function verifySecret(req,parsed){if(!WEBHOOK_SECRET)return true;return req.headers['x-crm-secret']===WEBHOOK_SECRET||parsed.query.secret===WEBHOOK_SECRET}
function requestJson(target,{method='GET',headers={},body:requestBody=null,auth=null,timeout=12000}={}){return new Promise((resolve,reject)=>{const u=new URL(target);const lib=u.protocol==='https:'?https:http;const opts={method,hostname:u.hostname,port:u.port||undefined,path:u.pathname+u.search,headers:{Accept:'application/json',...headers}};if(auth)opts.auth=auth;if(requestBody){const s=typeof requestBody==='string'?requestBody:JSON.stringify(requestBody);opts.headers['Content-Type']=opts.headers['Content-Type']||'application/json';opts.headers['Content-Length']=Buffer.byteLength(s);requestBody=s}const r=lib.request(opts,res=>{let b='';res.on('data',d=>b+=d);res.on('end',()=>{let j;try{j=JSON.parse(b)}catch{j={raw:b}};if(res.statusCode>=200&&res.statusCode<300)resolve(j);else reject(new Error(`HTTP ${res.statusCode}: ${b.slice(0,400)}`))})});r.setTimeout(timeout,()=>r.destroy(new Error('Request timeout')));r.on('error',reject);if(requestBody)r.write(requestBody);r.end()})}
function exotelStatus(s){s=String(s||'').toLowerCase();if(s==='completed')return'Connected';if(s==='no-answer'||s==='canceled')return'Missed';if(s==='busy')return'Busy';if(s==='failed')return'Failed';return s||'Unknown'}
async function syncExotel(db){const sid=process.env.EXOTEL_SID,key=process.env.EXOTEL_API_KEY,token=process.env.EXOTEL_API_TOKEN;if(!sid||!key||!token)return{ok:false,error:'Exotel credentials not configured',imported:0};const host=process.env.EXOTEL_API_HOST||'api.exotel.com';const endpoint=`https://${host}/v1/Accounts/${encodeURIComponent(sid)}/Calls.json?PageSize=100&SortBy=DateCreated:desc&details=true`;const data=await requestJson(endpoint,{auth:`${key}:${token}`});const calls=data.Calls||data.calls||[];let imported=0;for(const x of calls){const direction=String(x.Direction||'').toLowerCase().startsWith('in')?'Incoming':'Outgoing';const customerPhone=direction==='Incoming'?(x.From||x.from):(x.To||x.to);const c=upsertCustomer(db,{mobile:customerPhone,name:x.CallerName||'',source:'Exotel',provider:'Exotel',externalId:''});const rec=addCall(db,c,{externalId:x.Sid||x.sid,direction,provider:'Exotel',status:exotelStatus(x.Status||x.status),disposition:exotelStatus(x.Status||x.status)==='Connected'?'Connected':'Follow-up',duration:x.Duration||x.duration||x.ConversationDuration||0,recordingUrl:x.RecordingUrl||x.recording_url||'',at:x.DateCreated?new Date(String(x.DateCreated).replace(' ','T')+'Z').toISOString():new Date().toISOString(),from:x.From,to:x.To,rawStatus:x.Status});if(rec)imported++}if(imported)writeDb(db);return{ok:true,imported,total:calls.length,lastSync:new Date().toISOString()}}
function first(obj,paths){for(const p of paths){let v=obj;for(const k of p.split('.'))v=v&&v[k];if(v!==undefined&&v!==null&&v!=='')return v}return''}
function ingestGeneric(db,provider,x={}){const event=String(x.type||x.eventType||x.topic||x.event||'event');const mobile=first(x,['mobile','phone','waId','from','From','contact.phone','content.phone','content.contact.phone']);const email=first(x,['email','contact.email','content.email','content.contact.email']);const name=first(x,['name','username','contact.name','content.name'])||[first(x,['first_name','content.first_name']),first(x,['last_name','content.last_name'])].filter(Boolean).join(' ');const externalId=String(first(x,['externalId','id','webhook_id','messageId','whatsappMessageId','leadgen_id'])||'');const text=String(first(x,['text','message','body','content.message.message','content.text','data.text'])||event);const c=upsertCustomer(db,{mobile,email,name,source:provider,provider,externalId:first(x,['contactId','contact_id','content.id'])||''});addActivity(db,c,event,`${provider}: ${text}`,{provider,externalId});const leadTypes=['lead','enquiry','inquiry','add_to_cart','addtocart','abandoned_checkout','checkout_abandoned','wishlist','form_submit','customised_order','appointment','leadgen'];if(x.createLead||leadTypes.some(k=>event.toLowerCase().includes(k)))addLead(db,c,{source:x.source||provider,value:x.value||0,externalId:externalId?`lead-${externalId}`:''});if(x.channel||/message|chat|whatsapp|dm|reply/i.test(event))addMessage(db,c,{channel:x.channel||provider,provider,direction:x.direction||'in',text,externalId,at:x.at});return c}
async function ingestWebhook(provider,x,db){provider=provider.toLowerCase();let count=0;if(provider==='wati'){const mobile=x.waId||x.senderPhone||x.phone||x.from;const name=x.senderName||x.username||x.contactName||'';const text=x.text||x.message?.text||x.data?.text||x.eventType||'WhatsApp event';const c=upsertCustomer(db,{mobile,name,source:'WATI'});addMessage(db,c,{channel:'WhatsApp',provider:'WATI',direction:x.owner?'out':'in',text,externalId:x.whatsappMessageId||x.id,at:x.timestamp?new Date(Number(x.timestamp)*1000).toISOString():undefined});addActivity(db,c,x.eventType||'WhatsApp',`WATI: ${text}`,{provider:'WATI',externalId:x.id||x.whatsappMessageId});if(!x.owner)addLead(db,c,{source:'WATI WhatsApp',externalId:x.id?`lead-${x.id}`:''});count=1}
 else if(provider==='tidio'){const content=x.content||{};const phone=content.phone||content.contact?.phone;const email=content.email||content.contact?.email;const name=[content.first_name,content.last_name].filter(Boolean).join(' ')||content.name||'';const contactId=content.id||content.contact_id||content.contact?.id;const c=upsertCustomer(db,{mobile:phone,email,name,source:'Tidio',provider:'Tidio',externalId:contactId});const topic=x.topic||'Tidio event';let text=content.message?.message||content.message_content||content.text||topic;addActivity(db,c,topic,`Tidio: ${text}`,{provider:'Tidio',externalId:x.webhook_id});if(/message|replied|conversation|ticket/i.test(topic))addMessage(db,c,{channel:'Tidio',provider:'Tidio',direction:/operator/i.test(topic)?'out':'in',text,externalId:x.webhook_id,at:x.created_at?new Date(Number(x.created_at)*1000).toISOString():undefined});if(/contact.created|conversation|replied|ticket/i.test(topic))addLead(db,c,{source:'Tidio Chatbot',externalId:x.webhook_id?`lead-${x.webhook_id}`:''});count=1}
 else if(provider==='whatsapp'||provider==='meta'){const entries=x.entry||[];for(const ent of entries){for(const ch of ent.changes||[]){const v=ch.value||{};const contact=(v.contacts||[])[0]||{};for(const m of v.messages||[]){const c=upsertCustomer(db,{mobile:m.from,name:contact.profile?.name||'',source:'Meta WhatsApp'});const text=m.text?.body||m.button?.text||m.interactive?.button_reply?.title||`WhatsApp ${m.type||'message'}`;addMessage(db,c,{channel:'WhatsApp',provider:'Meta',direction:'in',text,externalId:m.id,at:m.timestamp?new Date(Number(m.timestamp)*1000).toISOString():undefined});addActivity(db,c,'WhatsApp Message',`Meta WhatsApp: ${text}`,{provider:'Meta',externalId:m.id});addLead(db,c,{source:'WhatsApp Meta Ad / DM',externalId:m.id?`lead-${m.id}`:''});count++}
 if(ch.field==='leadgen'&&v.leadgen_id){let lead={...v,type:'leadgen',source:'Meta Lead Ads',createLead:true,externalId:v.leadgen_id};if(process.env.META_PAGE_TOKEN){try{const gv=process.env.META_GRAPH_VERSION||'v23.0';const info=await requestJson(`https://graph.facebook.com/${gv}/${encodeURIComponent(v.leadgen_id)}?fields=id,created_time,field_data,ad_id,ad_name,campaign_id,campaign_name&access_token=${encodeURIComponent(process.env.META_PAGE_TOKEN)}`);const fields={};for(const f of info.field_data||[])fields[f.name]=(f.values||[])[0]||'';lead={...lead,...info,name:fields.full_name||fields.first_name||'',mobile:fields.phone_number||fields.phone||'',email:fields.email||'',text:`Meta Lead: ${info.campaign_name||info.ad_name||'Lead Form'}`,value:0}}catch(e){console.error('Meta lead detail fetch failed:',e.message)}}ingestGeneric(db,'Meta Lead Ads',lead);count++}for(const ld of v.leadgen||[]){ingestGeneric(db,'Meta Lead Ads',{...ld,type:'leadgen',source:'Meta Lead Ads',createLead:true});count++}}
 if(ent.messaging)for(const m of ent.messaging){const sender=m.sender?.id||'',text=m.message?.text||m.postback?.title||'Meta message';const c=upsertCustomer(db,{name:'Meta Contact',source:'Instagram/Facebook',provider:'Meta',externalId:sender});addMessage(db,c,{channel:'Meta DM',provider:'Meta',direction:'in',text,externalId:m.message?.mid});addActivity(db,c,'Meta DM',text,{provider:'Meta'});addLead(db,c,{source:'Instagram/Facebook DM',externalId:m.message?.mid?`lead-${m.message.mid}`:''});count++}}
 if(!count){ingestGeneric(db,'Meta',x);count=1}}
 else if(provider==='exotel'){const arr=Array.isArray(x)?x:[x];for(const a of arr){const direction=String(a.Direction||a.direction||'inbound').toLowerCase().startsWith('in')?'Incoming':'Outgoing';const mobile=direction==='Incoming'?(a.From||a.from):(a.To||a.to);const c=upsertCustomer(db,{mobile,source:'Exotel'});if(addCall(db,c,{externalId:a.Sid||a.CallSid||a.sid,direction,provider:'Exotel',status:exotelStatus(a.Status||a.status),duration:a.Duration||a.duration||0,recordingUrl:a.RecordingUrl||a.recording_url||'',from:a.From,to:a.To,rawStatus:a.Status}))count++}}
 else{ingestGeneric(db,provider,x);count=1}writeDb(db);return{ok:true,provider,count}}
const server=http.createServer(async(req,res)=>{
 if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type,X-CRM-Secret','Access-Control-Allow-Methods':'GET,POST,PATCH,PUT,DELETE'});return res.end()}
 const parsed=url.parse(req.url,true),p=parsed.pathname;
 if(p==='/api/login'&&req.method==='POST'){const x=await body(req);if(!ADMIN_PASSWORD||x.password===ADMIN_PASSWORD){const t=crypto.randomBytes(24).toString('hex');sessions.add(t);return send(res,200,{ok:true},'application/json',{'Set-Cookie':`crm_session=${t}; HttpOnly; SameSite=Lax; Path=/; Max-Age=43200`})}return send(res,401,{error:'Invalid password'})}
 if(p==='/api/auth'&&req.method==='GET')return send(res,200,{authenticated:authed(req),passwordEnabled:!!ADMIN_PASSWORD});
 if(!p.startsWith('/api/')){if(serveStatic(req,res))return;return send(res,404,'Not found','text/plain')}
 // Public provider webhooks. Protect with CRM_WEBHOOK_SECRET where the provider allows a secret query/header.
 if(p.startsWith('/api/webhooks/')){try{
   if(p==='/api/webhooks/meta'&&req.method==='GET'){const verify=process.env.WHATSAPP_VERIFY_TOKEN||process.env.META_VERIFY_TOKEN||'';if(parsed.query['hub.mode']==='subscribe'&&parsed.query['hub.verify_token']===verify)return send(res,200,String(parsed.query['hub.challenge']||''),'text/plain');return send(res,403,'Verification failed','text/plain')}
   const provider=p.split('/').filter(Boolean)[2]||'generic';
   if(!['meta','whatsapp','wati','tidio','exotel'].includes(provider)&&!verifySecret(req,parsed))return send(res,401,{error:'Invalid webhook secret'});
   const x=await body(req),db=readDb();
   if(provider==='customer-event'||provider==='website'||provider==='app'||provider==='generic'){if(!verifySecret(req,parsed))return send(res,401,{error:'Invalid webhook secret'});const c=ingestGeneric(db,x.provider||provider,x);writeDb(db);return send(res,200,{ok:true,customerId:c.id})}
   return send(res,200,await ingestWebhook(provider,x,db));
 }catch(e){console.error('Webhook error',e);return send(res,500,{error:e.message})}}
 if(!authed(req)&&p!=='/api/auth')return send(res,401,{error:'Unauthorized'});
 const db=readDb();
 try{
  if(p==='/api/dashboard'&&req.method==='GET'){const won=db.leads.filter(x=>x.stage==='Won'),pipeline=db.leads.reduce((a,l)=>(a[l.stage]=(a[l.stage]||0)+1,a),{});return send(res,200,{stats:{customers:db.customers.length,leads:db.leads.filter(l=>l.stage!=='Won').length,openTasks:db.tasks.filter(t=>t.status==='Open').length,pipelineValue:db.leads.filter(l=>l.stage!=='Won').reduce((s,l)=>s+Number(l.value||0),0),wonValue:won.reduce((s,l)=>s+Number(l.value||0),0)},pipeline,sourceReport:metricReport(db).slice(0,8)})}
  if(p==='/api/customers'&&req.method==='GET')return send(res,200,db.customers);
  if(p.startsWith('/api/customers/')&&req.method==='GET'){const id=p.split('/').pop(),c=db.customers.find(x=>x.id===id);if(!c)return send(res,404,{error:'Customer not found'});return send(res,200,{...c,activities:db.activities.filter(a=>a.customerId===id).sort((a,b)=>new Date(b.at)-new Date(a.at)),messages:db.messages.filter(m=>m.customerId===id).sort((a,b)=>new Date(a.at)-new Date(b.at)),leads:db.leads.filter(l=>l.customerId===id),tasks:db.tasks.filter(t=>t.customerId===id),calls:(db.calls||[]).filter(x=>x.customerId===id)})}
  if(p==='/api/leads'&&req.method==='GET')return send(res,200,db.leads);
  if(p.startsWith('/api/leads/')&&req.method==='PATCH'){const id=p.split('/').pop(),x=await body(req),l=db.leads.find(l=>l.id===id);if(!l)return send(res,404,{error:'Lead not found'});Object.assign(l,x);writeDb(db);return send(res,200,l)}
  if(p==='/api/tasks'&&req.method==='GET')return send(res,200,db.tasks);
  if(p.startsWith('/api/tasks/')&&req.method==='PATCH'){const id=p.split('/').pop(),x=await body(req),t=db.tasks.find(t=>t.id===id);if(!t)return send(res,404,{error:'Task not found'});Object.assign(t,x);writeDb(db);return send(res,200,t)}
  if(p==='/api/messages'&&req.method==='GET')return send(res,200,db.messages);
  if(p==='/api/lead-sources'&&req.method==='GET')return send(res,200,db.leadSources||[]);
  if(p==='/api/integrations'&&req.method==='GET'){const origin=`https://${req.headers.host}`;const data=(db.integrations||[]).map(i=>({...i,configured:i.env.length?i.env.every(k=>!!process.env[k]):i.status==='Ready',env:i.env.map(k=>({key:k,set:!!process.env[k]})),webhook:i.webhook?origin+i.webhook:''}));return send(res,200,data)}
  if(p==='/api/calls'&&req.method==='GET'){if(process.env.EXOTEL_SID&&process.env.EXOTEL_API_KEY&&process.env.EXOTEL_API_TOKEN){try{await syncExotel(db)}catch(e){console.error('Exotel auto-sync failed:',e.message)}}return send(res,200,readDb().calls||[])}
  if(p==='/api/integrations/exotel/sync'&&req.method==='POST'){const result=await syncExotel(db);return send(res,result.ok?200:400,result)}
  if(p==='/api/campaigns'&&req.method==='GET')return send(res,200,db.campaigns||[]);
  if(p==='/api/reports/sources'&&req.method==='GET')return send(res,200,metricReport(db));
  if(p==='/api/backup'&&req.method==='GET')return send(res,200,db,'application/json',{'Content-Disposition':'attachment; filename="dar-crm-backup.json"'});
  if(p==='/api/customers'&&req.method==='POST'){const x=await body(req);const c={id:newId('c'),tenantId:'dar',leadScore:50,ltv:0,status:'New',assignedTo:'u2',...x};db.customers.push(c);writeDb(db);return send(res,201,c)}
  if(p==='/api/leads'&&req.method==='POST'){const x=await body(req);const l={id:newId('l'),tenantId:'dar',stage:'New',createdAt:new Date().toISOString(),...x};db.leads.push(l);writeDb(db);return send(res,201,l)}
  if(p==='/api/tasks'&&req.method==='POST'){const x=await body(req);const t={id:newId('t'),tenantId:'dar',status:'Open',owner:'u2',...x};db.tasks.push(t);writeDb(db);return send(res,201,t)}
  if(p==='/api/calls'&&req.method==='POST'){const x=await body(req);db.calls??=[];const c={id:newId('call'),at:new Date().toISOString(),...x};db.calls.push(c);writeDb(db);return send(res,201,c)}
  if(p==='/api/activities'&&req.method==='POST'){const x=await body(req);const a={id:newId('a'),tenantId:'dar',at:new Date().toISOString(),...x};db.activities.push(a);writeDb(db);return send(res,201,a)}
  return send(res,404,{error:'API route not found'})
 }catch(e){console.error(e);return send(res,500,{error:e.message})}
});
server.listen(PORT,()=>console.log(`DAR CRM running on ${PORT}`));
